### ISSUE TITLE
Failed to boot into the game.

### ISSUE THREAD

**Issue by ghost** [minecraftabnormals/Neapolitan#173]
Start up crash.
1.19.2
[crash-2023-10-07_02.21.43-client.txt](https://github.com/team-abnormals/neapolitan/files/12836100/crash-2023-10-07_02.21.43-client.txt)

**Comment by bageldotjpg** [comment]
We recently reworked Milkshakes, and Twilight's Flavor Delight adds some, so this crash is caused due to that mod trying to reach old Milkshake code. Give them some time and hopefully they should fix it soon, I assume this issue also affects other addons. I would report it there though: https://github.com/Minecraft-LightLand/Twilight-Delight/issues
